### ISSUE TITLE
CompactArray rename

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [vigna/sux-rs#49]
I see that you renamed (https://github.com/vigna/sux-rs/commit/1f51f0c0874d60d57d924acc7e877fd17787d31a) `CompactArray` to `BitFieldVec`.

I much prefer `CompactArray`:
- `sucds` calls it [`CompactVec`](https://docs.rs/sucds/0.8.1/sucds/int_vectors/index.html) (which actually is a more accurate name)
- It indicates that a list of compact items is being stored.
- Whereas `BitField` reminds me of c++ bitfields, where multiple values in a struct are given a specific bit-width.
- And `BitField` also sounds like an integer that stores flag value constants that are or'ed together.
- But neither of the two above points is what this is used for, which is basically only storing plain integers.

Would you consider renaming it back to either `CompactArray` or `CompactVec`?

**Comment by vigna** [comment]
“Compact” sounds like some kind of compression is happening. Also, since we implement `BitFieldSlice` on slices of unsigned types with exactly the width of the type, in that case it is not compact at all—it is just the natural width.

“Compact array” or “compacted array” is also frequently used in succinct data structures to denote an array containing only non-zero values, and then there is a bit vector with one bit per position, with a one for non-zero value, and an associated ranking structure that recovers the correct position in the array of nonzero values.

We are aware that “bit field” in the C world refers to bit width of different width within a struct.

Most people would call it a `BitArray` or something like that, but then the associated slice would logically be `BitSlice` and we wanna keep that for slices of a bit vector in the future.

The point is that we're trying to describe what the structure _is_, not how the structure _behaves_, because in the second case the name will be obviously confusing to people that associate to that behavior another type of structure (see example above).

Said that, naming is always a question of personal taste. I'm not 100% happy with `BitFieldVec`, but I was totally uncomfortable with `CompactVec`.

**Comment by RagnarGrootKoerkamp** [comment]
Ok so the problem with `Bit` is that every time I see this name now, I think it's like a `u64` field with bitflags, as in, or-ing together some `READ=1`, `WRITE=2`, `APPEND=4`, ... constants to create a 'bit field'.

Currently I really like `Packed`. We call it '2-bit packing' of ACTG or 'bitpacking' in general, so `PackedVec` sounds very intuitive to me, while hopefully not having the wrong connotation of `Compact`. (It doesn't for me, but maybe does for you?)
